### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by illip** [chin-rcip/collections-model#44]
Hi all,

I don't think chin-rcip is a relevant name for our repository since we might need to create new ones for other projects (e.g. it might be useful for Nomenclature at some point). Also, if all of our projects are in the same repository, it will become a mess to manage the issues. While our repository doesn't have a big reach, I think it's the perfect time to rename it if needed.

In my opinion, I would go with something that covers the whole "Collections Model" (actors and objects facets) and all the relevant scripts to map the data against it. 

So I would simply recommend "collections-model". 

What do you think?

**Comment by stephenhart8** [comment]
collections_model is a good name for me (and indeed better than chin-rcip)

**Comment by VladimirAlexiev** [comment]
Isn't this focused more on CIC (Creators in Canada?) 
Modularity is definitely a good thing, and Artefacts (Collections) is a bigger can of worms.
(It is nice though that while discussing CIC, you're also looking forward to Artefacts issues.)

**Comment by illip** [comment]
Hi Vladimir, we have decided to distinguish *CiC* and *Collections Model* to avoid confusion. So *CiC* will be the interface where people will search for Canadian actors (`E39_Actor` meaning). *CiC* interface will be based on the *Collections Model*.

For the moment we work on the Actors facet of the "Collections Model" but the Objects facet will be part of the same model. Finally, the *Collections Model" will also be used by *Artefacts Canada*.

So I will close this issue since the change has been done. :)
