### ISSUE TITLE
Primitive values or XSD datatypes

### ISSUE THREAD

**Issue by illip** [chin-rcip/collections-model#48]
Currently in our Target Model 2.1 (will be released soon), we mention CRM's primitive values (e.g. `E62_String`) and XSD types (e.g. `xsd:dateTime`). I would recommend to harmonize our documentation by using only one representation.

Following this CRM's encoding rule:

>The primitive values "E60 Number", "E61 Time Primitive", "E62 String" and "E94 Space Primitive" referred in the Model for formal completeness are interpreted as rdf: literal. 

I think we should remove CRM's primitive values to avoid confusion. 

As far as I know, currently we just use `xsd:string` and `xsd:dateTime`.

What do you think?

**Comment by Habennin** [comment]
I +1 this. CIDOC CRM puts in the primitive data types as placeholders so as not to force the adopting institution to use particular kinds of data type. When it comes to standardised implementation, however, one should choose a consistent data type and document this. 

You do not also use rdfs:literal?

**Comment by illip** [comment]
@Habennin, I don't know if I understood your question about rdfs:Literal. In fact, our XSD datatypes are used precisely on rdfs:Literal as attributes. I don't know where we could apply them otherwise. :p Perhaps, I missed something! 

Currently, TM2.1 is not consistent in the use of XSD datatypes over primitive values. CHIN has decided to edit the documentation to remove all primitive value mentions and this will be done in the 2.1 version.

**Comment by illip** [comment]
All the primitive value mentions have been removed. We also replaced all the `xsd:date` by `xsd:dateTime` and edit the literals for `yyyy-mm-ddT00:00:00`.
